package nl.lolmewn.rug.quakesensor.gui;

import java.awt.EventQueue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import nl.lolmewn.rug.quakecommon.Threader;
import nl.lolmewn.rug.quakesensor.SensorMain;

/**
 *
 * @author Lolmewn
 */
public class MainGUI extends javax.swing.JFrame implements Runnable {

    private final SensorMain main;

    /**
     * Initializes the MainGUI
     *
     * @param main Main program
     */
    public MainGUI(SensorMain main) {
        this.main = main;
        this.setSize(400, 335);
        this.setResizable(false);
        initComponents();
        setVisible(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        loadServersToUI();
        initQuakeDrawer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.JTabbedPane();
        sensorPanel = new javax.swing.JPanel();
        sensorStatusLabel = new javax.swing.JLabel();
        statusField = new javax.swing.JLabel();
        quakeGraphPanel = new QuakeGraph();
        serversPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        serversTable = new javax.swing.JTable();
        addNewServerButton = new javax.swing.JButton();
        removeServerButton = new javax.swing.JButton();

        sensorStatusLabel.setText("Sensor status");

        statusField.setText("Starting...");

        javax.swing.GroupLayout quakeGraphPanelLayout = new javax.swing.GroupLayout(quakeGraphPanel);
        quakeGraphPanel.setLayout(quakeGraphPanelLayout);
        quakeGraphPanelLayout.setHorizontalGroup(
            quakeGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        quakeGraphPanelLayout.setVerticalGroup(
            quakeGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sensorPanelLayout = new javax.swing.GroupLayout(sensorPanel);
        sensorPanel.setLayout(sensorPanelLayout);
        sensorPanelLayout.setHorizontalGroup(
            sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sensorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sensorStatusLabel)
                    .addComponent(statusField))
                .addContainerGap(329, Short.MAX_VALUE))
            .addComponent(quakeGraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sensorPanelLayout.setVerticalGroup(
            sensorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sensorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sensorStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(quakeGraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Tabs.addTab("Sensor", sensorPanel);

        serversTable.setAutoCreateRowSorter(true);
        serversTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IP", "Port", "Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        serversTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(serversTable);
        if (serversTable.getColumnModel().getColumnCount() > 0) {
            serversTable.getColumnModel().getColumn(0).setResizable(false);
            serversTable.getColumnModel().getColumn(1).setResizable(false);
            serversTable.getColumnModel().getColumn(2).setResizable(false);
        }

        addNewServerButton.setText("Add new");
        addNewServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewServerButtonActionPerformed(evt);
            }
        });

        removeServerButton.setText("Remove selected");

        javax.swing.GroupLayout serversPanelLayout = new javax.swing.GroupLayout(serversPanel);
        serversPanel.setLayout(serversPanelLayout);
        serversPanelLayout.setHorizontalGroup(
            serversPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serversPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addNewServerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeServerButton)
                .addContainerGap())
        );
        serversPanelLayout.setVerticalGroup(
            serversPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serversPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(serversPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewServerButton)
                    .addComponent(removeServerButton))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        Tabs.addTab("Servers", serversPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNewServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewServerButtonActionPerformed
        AddNewServerPanel panel = new AddNewServerPanel() {
            @Override
            public void save(String IP, int port) {
                addServerToUI(IP, port, "Checking...");
                Threader.runTask(() -> {
                    boolean up = main.getServerManager().checkAvailability(IP, port);
                    EventQueue.invokeLater(() -> {
                        // Find idx for row
                        DefaultTableModel dtm = (DefaultTableModel) serversTable.getModel();
                        for (int row = 0; row < dtm.getRowCount(); row++) {
                            if (dtm.getValueAt(row, 0).equals(IP) && dtm.getValueAt(row, 1).equals(port)) {
                                dtm.setValueAt(up ? "Online" : "Offline", row, 2);
                            }
                        }
                    });
                });
            }
        };
        panel.setVisible(true);
    }//GEN-LAST:event_addNewServerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JButton addNewServerButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel quakeGraphPanel;
    private javax.swing.JButton removeServerButton;
    private javax.swing.JPanel sensorPanel;
    private javax.swing.JLabel sensorStatusLabel;
    private javax.swing.JPanel serversPanel;
    private javax.swing.JTable serversTable;
    private javax.swing.JLabel statusField;
    // End of variables declaration//GEN-END:variables

    private void loadServersToUI() {
        main.getServerManager().getServers().stream().forEach((server) -> {
            addServerToUI(server.getAddress().getAddress(), server.getAddress().getPort(), server.isConnected() ? "Online" : "Offline");
        });
    }

    private void addServerToUI(String IP, int port, String status) {
        DefaultTableModel dtm = (DefaultTableModel) serversTable.getModel();
        dtm.addRow(new Object[]{IP, port, status});
    }

    private void initQuakeDrawer() {
        Threader.runTask(this);
    }

    @Override
    public void run() {
        while (true) {
            this.quakeGraphPanel.repaint();
            try {
                Thread.sleep(1000 / SensorMain.POLLS_PER_SECOND);
            } catch (InterruptedException ex) {
                Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
